### ISSUE TITLE
Update source and binary dependencies in debian/control, and any sh-bangs to python3

### ISSUE THREAD

**Issue by lene** [lene/nicotine-plus#18]

**Comment by lene** [comment]
https://github.com/Nicotine-Plus/nicotine-plus/pull/106#discussion_r389864509: 
> If you get a chance, try and find a way to use [the test suite] from DEP-8 as well. We have a basic stub in debian/tests/control already.

**Comment by teadur** [comment]
libgirepository1.0-dev required on debian buster to build pygobject
