### ISSUE TITLE
Download fails for arbitrary UTF-8 filenames

### ISSUE THREAD

**Issue by lene** [lene/nicotine-plus#25]
File "/nicotine/pynicotine/transfers.py", line 1013, in _FileRequestDownload
    if os.access(winfname, os.F_OK):
UnicodeEncodeError: 'ascii' codec can't encode character '\u039d' in position 61: ordinal not in range(128)

**Comment by droserasprout** [comment]
Could you please provide user+path of particular file to reproduce this issue?

**Comment by lene** [comment]
Well...
```
Traceback (most recent call last):
  File "/nicotine/pynicotine/gtkgui/search.py", line 1644, in OnCopyURL
    self.frame.SetClipboardURL(user, path)
  File "/nicotine/pynicotine/gtkgui/frame.py", line 2778, in SetClipboardURL
    self.clip.set_text("slsk://" + urllib.request.pathname2url("%s/%s" % (user, path.replace("\\", "/"))))
TypeError: Gtk.Clipboard.set_text() takes exactly 3 arguments (2 given)
```
Seems I'll have to take care of that first.
I can already say that 1) this is not limited to any particular user or file, and 2) the exception only occurs when the download is started, not while it is queued.

**Comment by lene** [comment]
Here's an example: slsk://0x00/%40%40dvlsv/Music/Psarantonis/%CE%9A%CE%BF%CF%85%CE%BC%CE%B5%CE%BD%CF%84%CE%AC%CE%BA%CE%B7%CF%82%20-%20%CE%9B%CE%BF%CF%85%CE%B4%CE%BF%CE%B2%CE%AF%CE%BA%CE%BF%CF%82%20-%20%CE%9E%CF%85%CE%B4%CE%AC%CE%BA%CE%B7%CF%82%20-%20%CE%A8%CE%B1%CF%81%CE%B1%CE%BD%CF%84%CF%8E%CE%BD%CE%B7%CF%82%20-%20%CE%A4%CE%AD%CF%83%CF%83%CE%B5%CF%81%CE%B9%CF%82%20%CE%B4%CF%81%CF%8C%CE%BC%CE%BF%CE%B9%20%CE%B3%CE%B9%CE%B1%20%CF%84%CE%BF%CE%BD%20%CE%95%CF%81%CF%89%CF%84%CF%8C%CE%BA%CF%81%CE%B9%CF%84%CE%BF%20%282000%29%20-%20FLAC/20%20-%20%CE%A3%CE%B1%CE%BC%CE%B9%CE%B1%CE%BC%CE%AF%CE%B4%CE%B9.flac

**Comment by droserasprout** [comment]
Not sure about what commit exactly fixes this, but I can't reproduce this on my branch:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/10263434/80017199-e2257a80-84dc-11ea-9f04-f5b5de896d55.png">

(first download was aborted intentionally)

**Comment by lene** [comment]
This error occurs if the locale is not set to a UTF-8 locale (as is the case on a fresh docker image). #61 sets the locale for the docker image used in testing, so this does no longer happen.
